name: news-crawler-schedule

on:
  schedule:
    # GitHub cron 用 UTC！台北 15:30 = UTC 07:30
    - cron: '30 7 * * 1-5'
  workflow_dispatch:  # 手動按按鈕也能觸發（方便除錯）

jobs:
  crawl:
    runs-on: ubuntu-latest

    env:                        # 這些值來自 Secrets

